main: dr.mz27.Deathrain
version: 1.0.2-beta
name: Deathrain
author: Benjamin Martinez
api-version: 1.21

commands:
    deathrain:
        description: Deathrain command
        aliases:
            - dr